CREATE TABLE IF NOT EXISTS admins (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skulls (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL,
  link_url TEXT NOT NULL,
  link_text VARCHAR(100) DEFAULT 'Подробнее',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO admins (username, password_hash) VALUES 
  ('admin1', '$2b$10$rZ8F5QXZ5xqGZqK5nJ5Q0eH5wX5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5'),
  ('admin2', '$2b$10$rZ8F5QXZ5xqGZqK5nJ5Q0eH5wX5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5')
ON CONFLICT (username) DO NOTHING;